### ISSUE TITLE
Bug — Schedule saving for user no longer works

### ISSUE THREAD

**Issue by jshom** [YACS-RCOS/yacs.n#119]
**Describe the bug**
I tried to sign in and add courses and have them saved but this functionality failed

**To Reproduce**
1. Go to any recent deploy
2. Sign up
3. Import CSV for Fall2020 RPI
4. Go to homepage
5. Add course
6. Add to calendar

**Expected behavior**
Expect after a refresh that the same courses and schedule appears

**Screenshots**
![Kapture 2020-04-21 at 22 16 04](https://user-images.githubusercontent.com/11034221/79933343-c909c480-841d-11ea-9266-61b942e04964.gif)

**Desktop (please complete the following information):**
 - Mac OS Safari

**Additional context**
This may have to do with the way we store sessions, lets try to use flask sessions and remove the db session we created prior

**Comment by CoreyBuckley** [comment]
I believe this happens because the name of a cookie changed that the user loaded courses functionality was dependent on. Need to change this block of code to use `userID` instead
https://github.com/YACS-RCOS/yacs.n/blob/17128706b79dec8fdb5b377dbcdd8181ea31e0ee/src/web/src/components/Header.vue#L107-L129
