### ISSUE TITLE
Bug — Conflict course remains selected

### ISSUE THREAD

**Issue by CoreyBuckley** [YACS-RCOS/yacs.n#150]
**Describe the bug**
When you click on a course in the course list that has a conflict with the existing schedule, the notification comes up saying it couldn't be added, yet the course remains highlighted in the list.

**To Reproduce**
1. On schedule page select at least one pair of conflicting courses
2. Observe that the conflicting course you attempted to add remains highlighted in the course list.

**Expected behavior**
The course should not be highlighted since that indicates it's part of the schedule. (An icon to differentiate non-compatible courses in the course list would be better.)

**Screenshots**
![bug](https://user-images.githubusercontent.com/28029704/83809326-3eef8580-a684-11ea-914d-33974e3f732d.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**Comment by 123joshuawu** [comment]
@CoreyBuckley I believe this was the intended behavior. 

In hindsight, this is probably not so user friendly, but the highlighted state in `CourseList` actually refers to `SelectedCourses` and not the schedule. 

Selecting a course in `CourseList` adds the `Course` to `SelectedCourses` and adds its first non-conflicting `CourseSection` to the `Schedule`. If there are no non-conflicting `CourseSection`s, the `Course` is still added to `SelectedCourses` hence it is grayed out in `CourseList`. 

My thinking is users should be using `CourseList` to find courses that they are interested in, add courses that they want to take to `SelectedCourses`, then work out a schedule with the course sections.

So I believe the use case pushes us to separate `CourseList` and `SelectedCourses` to different pages and have the user progress from `CourseList` page to `SelectedCourses` page instead of swapping between tabs. This would reflect the distinction between two use cases of YACS, course exploration and course scheduling.

**Comment by CoreyBuckley** [comment]
> I believe this was the intended behavior.
> 
> In hindsight, this is probably not so user friendly, but the highlighted state in `CourseList` actually refers to `SelectedCourses` and not the schedule.
> 
> Selecting a course in `CourseList` adds the `Course` to `SelectedCourses` and adds its first non-conflicting `CourseSection` to the `Schedule`. If there are no non-conflicting `CourseSection`s, the `Course` is still added to `SelectedCourses` hence it is grayed out in `CourseList`.
> 
> My thinking is users should be using `CourseList` to find courses that they are interested in, add courses that they want to take to `SelectedCourses`, then work out a schedule with the course sections.
> 
> So I believe the use case pushes us to separate `CourseList` and `SelectedCourses` to different pages and have the user progress from `CourseList` page to `SelectedCourses` page instead of swapping between tabs. This would reflect the distinction between two use cases of YACS, course exploration and course scheduling.

@123joshuawu  Do we need a separate page for selected courses? To me, a course being selected is synonymous with it being visible on the schedule. I guess the semantics might be confusing me a bit. Selected courses seems intended to be more like 'Desired courses' or 'Want to take'.

A separate page for inputting some subset of courses that are a 'must have' and then generating a schedule makes sense (I know that's one of the features somewhere in the issues..)

Just my thoughts 💭

**Comment by 123joshuawu** [comment]
@CoreyBuckley Okay I see what you mean.

So yes, the end goal is for users to not have to deal with course sections, rather users should be able to choose from multiple schedules automatically generated from courses selected in `CourseList` (which would effectively eliminate the need for `SelectedCourses` view).

I guess the main thing right now is just having the course search and filter functionality (total set of courses) separate from the subset of courses that are in the schedule.

But I agree that the semantics are not clear. Probably because I wasn't too sure of the semantics myself when I pushed the features 😎

Some page planning should help avoid this in the next iteration.
